// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jpm5nL-Hi4pTtZWrwv2mshWXkHGwGGc',
    appId: '1:44439246371:web:90e96ab6c0c396765d8396',
    messagingSenderId: '44439246371',
    projectId: 'solicitudes-a0a5f',
    authDomain: 'solicitudes-a0a5f.firebaseapp.com',
    storageBucket: 'solicitudes-a0a5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjf-37_kLy5_FfK_U5ft7itr2q0-yWp5g',
    appId: '1:44439246371:android:0742a26a794b4a5d5d8396',
    messagingSenderId: '44439246371',
    projectId: 'solicitudes-a0a5f',
    storageBucket: 'solicitudes-a0a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsN_LMgT_7JeJxof6OWyO98YfHdsykNqU',
    appId: '1:44439246371:ios:31fd18591f7343375d8396',
    messagingSenderId: '44439246371',
    projectId: 'solicitudes-a0a5f',
    storageBucket: 'solicitudes-a0a5f.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
